### ISSUE TITLE
-s tag not working in compare_states.py

### ISSUE THREAD

**Issue by typeparameter** [elnardu/cs252#1]
The `-s` tag is not working when running test_simple5 or test_simple6. Any reason why this would be?

**Comment by elnardu** [comment]
Can you redownload the thing and check? 
Also, how exactly are you using it?

**Comment by typeparameter** [comment]
`python3 compare_states.py -s test_simple6` or `python3 compare_states test_simple6 -s`. Neither work

**Comment by elnardu** [comment]
I thought that was the case. You need to put a number there. I updated the readme

**Comment by typeparameter** [comment]
That worked!
